version: '3.8'

services:
  db-bpmn:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: BPMN_db
    volumes:
      - db-bpmn-data:/var/lib/postgresql/data
    networks:
      - bpmn-network

  hasura-bpmn: 
       image: hasura/graphql-engine:latest
       ports:
         - 8080:8080
       depends_on:
         - db-bpmn
       environment:
         HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgres@db-bpmn:5432/BPMN_db
         HASURA_GRAPHQL_ENABLE_TELEMETRY: "false"
         HASURA_GRAPHQL_ENABLE_CONSOLE: "true"

networks:
  bpmn-network:
    driver: bridge

volumes:
  db-bpmn-data:


  